### ISSUE TITLE
NewHttpMessageHandler is keep getting invoked, even though connection is dropped.

### ISSUE THREAD

**Issue by cemahseri** [TechnikEmpire/CitadelCore.Windows#21] opened 2020-06-05 10:01 UTC
Hello there!

I've made an example URL filtering application and it works so far so good. It blocks the connection and the specific element doesn't appears on the browser. I'm also trying to analyze to see which filters are being used more frequently than the others. It basically keeps count of blocked URLs into a text file. This also works okay but sometimes it starts to block an URL over and over and over again for literally no reason. Even if I close the browser, it'll keep blocking it.

Versions I'm using, by the way;
**CitadelCore.Windows:** 4.2.5
**DistillNET:** 1.6.6

There is a on/off switch. It literally sets a boolean to true or false. When method *(which I've combined with the NewHttpMessageHandler)* is getting invoked, it checks if it's true or false and if it's false, it'll just return. Here's my code;
```csharp
private void OnNewMessage(HttpMessageInfo messageInfo)
{
    if (!Enabled)
    {
        return;
    }

    if (messageInfo.MessageType == MessageType.Request && messageInfo.MessageProtocol == MessageProtocol.Http || messageInfo.MessageProtocol == MessageProtocol.WebSocket
        && filters.Any(f => messageInfo.MessageProtocol == MessageProtocol.Http && f.Options != UrlFilter.UrlFilterOptions.Websocket && f.IsMatch(messageInfo.Url, messageInfo.Headers)))
    {
        messageInfo.MessageType = MessageType.Response;
        messageInfo.ProxyNextAction = ProxyNextAction.DropConnection;

        LogTheRule(messageInfo);
        return;
    }

    messageInfo.ProxyNextAction = ProxyNextAction.AllowAndIgnoreContent;
}
```

Here is what debug file looks like;
```
6/5/2020 3:33:57 AM  --  Rule: @@||accounts.google.com^$document,subdocument,domain=adwords.google.com
6/5/2020 3:33:57 AM  --  Rule: @@||accounts.google.com^$document,subdocument,domain=adwords.google.com
6/5/2020 3:34:00 AM  --  Rule: @@||accounts.google.com^$document,subdocument,domain=adwords.google.com
6/5/2020 3:34:01 AM  --  Rule: @@||accounts.google.com^$document,subdocument,domain=adwords.google.com
6/5/2020 3:35:00 AM  --  Rule: @@||accounts.google.com^$document,subdocument,domain=adwords.google.com
6/5/2020 3:35:00 AM  --  Rule: @@||accounts.google.com^$document,subdocument,domain=adwords.google.com
6/5/2020 3:36:00 AM  --  Rule: @@||accounts.google.com^$document,subdocument,domain=adwords.google.com
6/5/2020 3:38:11 AM  --  Rule: @@||accounts.google.com^$document,subdocument,domain=adwords.google.com
6/5/2020 3:39:00 AM  --  Rule: @@||accounts.google.com^$document,subdocument,domain=adwords.google.com
6/5/2020 3:41:00 AM  --  Rule: @@||accounts.google.com^$document,subdocument,domain=adwords.google.com
6/5/2020 3:41:00 AM  --  Rule: @@||accounts.google.com^$document,subdocument,domain=adwords.google.com
6/5/2020 3:41:00 AM  --  Rule: @@||accounts.google.com^$document,subdocument,domain=adwords.google.com
6/5/2020 3:41:00 AM  --  Rule: @@||accounts.google.com^$document,subdocument,domain=adwords.google.com
6/5/2020 3:41:00 AM  --  Rule: @@||accounts.google.com^$document,subdocument,domain=adwords.google.com
6/5/2020 3:42:00 AM  --  Rule: @@||accounts.google.com^$document,subdocument,domain=adwords.google.com
6/5/2020 3:42:00 AM  --  Rule: @@||accounts.google.com^$document,subdocument,domain=adwords.google.com
6/5/2020 3:42:00 AM  --  Rule: @@||accounts.google.com^$document,subdocument,domain=adwords.google.com
6/5/2020 3:43:00 AM  --  Rule: @@||accounts.google.com^$document,subdocument,domain=adwords.google.com
6/5/2020 3:43:00 AM  --  Rule: @@||accounts.google.com^$document,subdocument,domain=adwords.google.com
6/5/2020 3:43:35 AM  --  Rule: @@||accounts.google.com^$document,subdocument,domain=adwords.google.com
6/5/2020 3:43:42 AM  --  Rule: @@||accounts.google.com^$document,subdocument,domain=adwords.google.com
6/5/2020 3:43:42 AM  --  Rule: @@||accounts.google.com^$document,subdocument,domain=adwords.google.com
6/5/2020 3:43:42 AM  --  Rule: @@||accounts.google.com^$document,subdocument,domain=adwords.google.com
6/5/2020 3:43:42 AM  --  Rule: @@||accounts.google.com^$document,subdocument,domain=adwords.google.com
6/5/2020 3:43:46 AM  --  Rule: @@||accounts.google.com^$document,subdocument,domain=adwords.google.com
6/5/2020 3:43:46 AM  --  Rule: @@||accounts.google.com^$document,subdocument,domain=adwords.google.com
6/5/2020 3:43:46 AM  --  Rule: @@||accounts.google.com^$document,subdocument,domain=adwords.google.com
6/5/2020 3:43:46 AM  --  Rule: @@||accounts.google.com^$document,subdocument,domain=adwords.google.com
6/5/2020 3:44:00 AM  --  Rule: @@||accounts.google.com^$document,subdocument,domain=adwords.google.com
6/5/2020 3:45:01 AM  --  Rule: @@||accounts.google.com^$document,subdocument,domain=adwords.google.com
6/5/2020 3:46:00 AM  --  Rule: @@||accounts.google.com^$document,subdocument,domain=adwords.google.com
6/5/2020 3:46:00 AM  --  Rule: @@||accounts.google.com^$document,subdocument,domain=adwords.google.com
6/5/2020 3:48:00 AM  --  Rule: @@||accounts.google.com^$document,subdocument,domain=adwords.google.com
6/5/2020 3:52:00 AM  --  Rule: @@||accounts.google.com^$document,subdocument,domain=adwords.google.com
6/5/2020 3:52:01 AM  --  Rule: @@||accounts.google.com^$document,subdocument,domain=adwords.google.com
6/5/2020 3:53:00 AM  --  Rule: @@||accounts.google.com^$document,subdocument,domain=adwords.google.com
6/5/2020 3:56:00 AM  --  Rule: @@||accounts.google.com^$document,subdocument,domain=adwords.google.com
6/5/2020 3:57:00 AM  --  Rule: @@||accounts.google.com^$document,subdocument,domain=adwords.google.com
6/5/2020 4:04:01 AM  --  Rule: @@||accounts.google.com^$document,subdocument,domain=adwords.google.com
6/5/2020 4:04:01 AM  --  Rule: @@||accounts.google.com^$document,subdocument,domain=adwords.google.com
6/5/2020 4:12:00 AM  --  Rule: @@||accounts.google.com^$document,subdocument,domain=adwords.google.com
6/5/2020 4:17:11 AM  --  Rule: @@||accounts.google.com^$document,subdocument,domain=adwords.google.com
6/5/2020 4:18:00 AM  --  Rule: @@||accounts.google.com^$document,subdocument,domain=adwords.google.com
6/5/2020 4:28:00 AM  --  Rule: @@||accounts.google.com^$document,subdocument,domain=adwords.google.com
6/5/2020 4:28:01 AM  --  Rule: @@||accounts.google.com^$document,subdocument,domain=adwords.google.com
6/5/2020 4:31:32 AM  --  Rule: @@||accounts.google.com^$document,subdocument,domain=adwords.google.com
6/5/2020 4:31:32 AM  --  Rule: @@||accounts.google.com^$document,subdocument,domain=adwords.google.com
6/5/2020 4:32:00 AM  --  Rule: @@||accounts.google.com^$document,subdocument,domain=adwords.google.com
6/5/2020 4:32:00 AM  --  Rule: @@||accounts.google.com^$document,subdocument,domain=adwords.google.com
6/5/2020 4:32:00 AM  --  Rule: @@||accounts.google.com^$document,subdocument,domain=adwords.google.com
6/5/2020 4:32:00 AM  --  Rule: @@||accounts.google.com^$document,subdocument,domain=adwords.google.com
6/5/2020 4:32:00 AM  --  Rule: @@||accounts.google.com^$document,subdocument,domain=adwords.google.com
6/5/2020 4:32:00 AM  --  Rule: @@||accounts.google.com^$document,subdocument,domain=adwords.google.com
6/5/2020 4:32:00 AM  --  Rule: @@||accounts.google.com^$document,subdocument,domain=adwords.google.com
6/5/2020 4:33:00 AM  --  Rule: @@||accounts.google.com^$document,subdocument,domain=adwords.google.com
6/5/2020 4:33:00 AM  --  Rule: @@||accounts.google.com^$document,subdocument,domain=adwords.google.com
6/5/2020 4:33:00 AM  --  Rule: @@||accounts.google.com^$document,subdocument,domain=adwords.google.com
6/5/2020 4:33:00 AM  --  Rule: @@||accounts.google.com^$document,subdocument,domain=adwords.google.com
6/5/2020 4:33:00 AM  --  Rule: @@||accounts.google.com^$document,subdocument,domain=adwords.google.com
6/5/2020 4:34:00 AM  --  Rule: @@||accounts.google.com^$document,subdocument,domain=adwords.google.com
6/5/2020 4:34:00 AM  --  Rule: @@||accounts.google.com^$document,subdocument,domain=adwords.google.com
6/5/2020 4:34:00 AM  --  Rule: @@||accounts.google.com^$document,subdocument,domain=adwords.google.com
6/5/2020 4:34:00 AM  --  Rule: @@||accounts.google.com^$document,subdocument,domain=adwords.google.com
6/5/2020 4:34:00 AM  --  Rule: @@||accounts.google.com^$document,subdocument,domain=adwords.google.com
6/5/2020 4:36:00 AM  --  Rule: @@||accounts.google.com^$document,subdocument,domain=adwords.google.com
6/5/2020 4:37:00 AM  --  Rule: @@||accounts.google.com^$document,subdocument,domain=adwords.google.com
6/5/2020 4:37:00 AM  --  Rule: @@||accounts.google.com^$document,subdocument,domain=adwords.google.com
6/5/2020 4:37:01 AM  --  Rule: @@||accounts.google.com^$document,subdocument,domain=adwords.google.com
6/5/2020 4:37:01 AM  --  Rule: @@||accounts.google.com^$document,subdocument,domain=adwords.google.com
6/5/2020 4:37:01 AM  --  Rule: @@||accounts.google.com^$document,subdocument,domain=adwords.google.com
6/5/2020 4:39:00 AM  --  Rule: @@||accounts.google.com^$document,subdocument,domain=adwords.google.com
6/5/2020 4:42:00 AM  --  Rule: @@||accounts.google.com^$document,subdocument,domain=adwords.google.com
6/5/2020 4:43:00 AM  --  Rule: @@||accounts.google.com^$document,subdocument,domain=adwords.google.com
6/5/2020 4:43:00 AM  --  Rule: @@||accounts.google.com^$document,subdocument,domain=adwords.google.com
6/5/2020 4:43:11 AM  --  Rule: @@||accounts.google.com^$document,subdocument,domain=adwords.google.com
6/5/2020 4:43:11 AM  --  Rule: @@||accounts.google.com^$document,subdocument,domain=adwords.google.com
6/5/2020 4:43:11 AM  --  Rule: @@||accounts.google.com^$document,subdocument,domain=adwords.google.com
6/5/2020 4:54:01 AM  --  Rule: @@||accounts.google.com^$document,subdocument,domain=adwords.google.com
6/5/2020 4:55:00 AM  --  Rule: @@||accounts.google.com^$document,subdocument,domain=adwords.google.com
6/5/2020 4:55:00 AM  --  Rule: @@||accounts.google.com^$document,subdocument,domain=adwords.google.com
6/5/2020 4:55:00 AM  --  Rule: @@||accounts.google.com^$document,subdocument,domain=adwords.google.com
6/5/2020 4:55:00 AM  --  Rule: @@||accounts.google.com^$document,subdocument,domain=adwords.google.com
6/5/2020 4:55:00 AM  --  Rule: @@||accounts.google.com^$document,subdocument,domain=adwords.google.com
6/5/2020 5:00:11 AM  --  Rule: @@||accounts.google.com^$document,subdocument,domain=adwords.google.com
6/5/2020 5:15:11 AM  --  Rule: @@||accounts.google.com^$document,subdocument,domain=adwords.google.com
6/5/2020 5:19:00 AM  --  Rule: @@||accounts.google.com^$document,subdocument,domain=adwords.google.com
6/5/2020 5:19:00 AM  --  Rule: @@||accounts.google.com^$document,subdocument,domain=adwords.google.com
6/5/2020 5:19:00 AM  --  Rule: @@||accounts.google.com^$document,subdocument,domain=adwords.google.com
6/5/2020 5:19:00 AM  --  Rule: @@||accounts.google.com^$document,subdocument,domain=adwords.google.com
6/5/2020 5:19:00 AM  --  Rule: @@||accounts.google.com^$document,subdocument,domain=adwords.google.com
6/5/2020 5:21:11 AM  --  Rule: @@||accounts.google.com^$document,subdocument,domain=adwords.google.com
6/5/2020 5:36:00 AM  --  Rule: @@||accounts.google.com^$document,subdocument,domain=adwords.google.com
6/5/2020 5:41:11 AM  --  Rule: @@||accounts.google.com^$document,subdocument,domain=adwords.google.com
6/5/2020 5:41:11 AM  --  Rule: @@||accounts.google.com^$document,subdocument,domain=adwords.google.com
6/5/2020 5:42:00 AM  --  Rule: @@||accounts.google.com^$document,subdocument,domain=adwords.google.com
6/5/2020 5:43:00 AM  --  Rule: @@||accounts.google.com^$document,subdocument,domain=adwords.google.com
6/5/2020 5:46:00 AM  --  Rule: @@||accounts.google.com^$document,subdocument,domain=adwords.google.com
6/5/2020 5:52:01 AM  --  Rule: @@||accounts.google.com^$document,subdocument,domain=adwords.google.com
6/5/2020 5:57:11 AM  --  Rule: @@||accounts.google.com^$document,subdocument,domain=adwords.google.com
6/5/2020 6:03:01 AM  --  Rule: @@||accounts.google.com^$document,subdocument,domain=adwords.google.com
6/5/2020 6:04:00 AM  --  Rule: @@||accounts.google.com^$document,subdocument,domain=adwords.google.com
6/5/2020 6:07:00 AM  --  Rule: @@||accounts.google.com^$document,subdocument,domain=adwords.google.com
6/5/2020 6:07:00 AM  --  Rule: @@||accounts.google.com^$document,subdocument,domain=adwords.google.com
6/5/2020 6:07:00 AM  --  Rule: @@||accounts.google.com^$document,subdocument,domain=adwords.google.com
6/5/2020 6:18:11 AM  --  Rule: @@||accounts.google.com^$document,subdocument,domain=adwords.google.com
6/5/2020 6:24:11 AM  --  Rule: @@||accounts.google.com^$document,subdocument,domain=adwords.google.com
6/5/2020 6:28:00 AM  --  Rule: @@||accounts.google.com^$document,subdocument,domain=adwords.google.com
6/5/2020 6:39:01 AM  --  Rule: @@||accounts.google.com^$document,subdocument,domain=adwords.google.com
6/5/2020 6:45:01 AM  --  Rule: @@||accounts.google.com^$document,subdocument,domain=adwords.google.com
```

**Comment by TechnikEmpire** [comment] 2020-06-06 02:33
I'm not seeing any problem here. If the problem is solely that the same rule is hitting multiple times per second, you should open the debug console on chrome and see just how many dozens of requests are made to dozens of domains with every page you visit.

Closing as there doesn't appear to be any issue here.

**Closed by TechnikEmpire** 2020-06-06 02:33 UTC

**Comment by TechnikEmpire** [comment] 2020-06-06 02:35
The driver code makes it impossible to intercept your own process,  so even the "block after closing " is explained away by the simple fact that closing a browser does not mean that the process is immediately terminated.
